DROP TABLE IF EXISTS COVID_DATA;


CREATE TABLE COVID_DATA (
  id BIGINT(10) NOT NULL,
  date VARCHAR(10) NOT NULL,
  state VARCHAR(100) NOT NULL,
  district VARCHAR(100) NOT NULL,
  tested VARCHAR(10) NOT NULL,
  confirmed VARCHAR(10) NOT NULL,
  recovered VARCHAR(10) NOT NULL
);